server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  # Tracks log positions

clients:
  - url: http://192.168.7.105:3100/loki/api/v1/push

scrape_configs:
  - job_name: "scm-backend-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "scm-backend-logs"
          __path__: "/var/logs/*.log"
