server:
  port: 8082

spring:
  application:
    name: HotelService

  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: heyAlok6282@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "configserver:http://localhost:8085/"